### ISSUE TITLE
Bluemix deploy 404 not found

### ISSUE THREAD

**Issue by toanxyz** [nmtoan07/bluemix-aspnetcore-starter#1]
I created the new application using visual 2017 template and it doesn't work. After deploying to IBM Bluemix, the error is shown.
"404 not found: Requested route ('app.domain') does not exist"

**Comment by toanxyz** [comment]
First of all, we need to install the nuget package for the extension method: AddCommandLine
```Microsoft.Extensions.Configuration.CommandLine```
The Program.cs must be:
```
public class Program
    {
        public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseConfiguration(config)
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();

            host.Run();
        }
    }
```

The important configuration is .UseConfiguration(config). Without this configuration, the application will start on the locahost:5000 and it will not work.
In the runtime, Bluemix will use command config to setup the PORT and other things.
The working log should be `Now listening on: http://0.0.0.0:8080`

**Comment by toanxyz** [comment]
The other important thing is the manifest.yml file:
```
applications:
- name: bluemix-aspnetcore-starter
  host: aspnetcore-starter
  domain: mybluemix.net
  memory: 512M
  buildpack: https://github.com/cloudfoundry/dotnet-core-buildpack.git
```

This will use the latest buildpack, the current default buildpack of blumix is still the old version.
We can change the name and the host information, the host will be the url of this application.
